# The database migrations path used for integration tests. Set this value to the
# root directory of the database migrations. These migrations are called for each
# isolated integration test to provide a clean database.
migrations.dir = "/path/to/db/migrations"

# Allowed origins for which you want to allow browser/client access to
# authenticated endpoints. The value must be comma delimited.
allowed.origins = "http://localhost:8181"

# Credentials for integrating with the GitHub OAuth API.
gh.client.id = "..."
gh.client.secret = "..."

# The PostgreSQL database connection string.
database.url = "postgres://<user>:<password>@:<port>/<db>?..."

# The PostgreSQL database connection string for tests.
test.database.url = "postgres://<user>:<password>@:<port>/<db>?..."

# Logging values to define the logging level and if text or JSON output is
# preferred. The level must be one of (panic|fatal|error|warn|info|debug|trace)
# and the format must be one of (text|json).
log.format = "text"
log.level = "info"

# The atlas server HTTP settings.
#
# Defines the HTTP listening address
listen.addr = "localhost:8080"
#
# Define the HTTP read timeout as a duration.
http.read.timeout = "15s"
#
# Define the HTTP write timeout as a duration.
http.write.timeout = "15s"

# Enable development settings. This is typically used when running the service
# locally mimicking a non-production environment. Must be (true|false).
dev = false

# The base64 encoded session key used to encrypt and authenticate user session
# cookies. It is recommended to use a key with 32 or 64 bytes.
session.key = "UIla7DSIVXzhvd9yHxexEExel9HQpSCQ+Rsn3y+e2Rs="

# The SendGrid API key used for sending email confirmation requests.
sendgrid.api.key = "..."

# The domain name used for sending email confirmation requests.
domain.name = "https://atlas.cosmos.network"

# The syslog destination address for log streaming.
syslog.addr = "logsN.logs.com:XXXX"

# The ipstack API key for geolocation functionality.
ipstack.key = "013d2f2737f1353bc000f1ed4d61ed44"

# The interval in which to retrigger a node crawl after the node pool is
# exhausted.
node.crawl.interval = "5m"

# The interval in which to recheck nodes for availability.
node.recheck.interval = "1h"

# The size of the reseed list for which to reseed the node pool after it has
# been exhausted. It is populated by the crawling process.
node.reseed.size = 100

# The initial list of comma-delimited seed nodes to crawl.
node.seeds = "http://1.255.51.125:26657,..."
